spring:
  profiles:
    active: dev
  servlet:
    # 上传文件配置
    multipart:
      # 文件上传存放的位置
      location: /home/binji/file/spring-boot-demo/${env}
      # 限制单个文件大小
      max-file-size: 10MB
      # 限制所有文件总大小
      max-request-size: 2048MB


# 指定logback日志配置文件
#logging:
#  config: classpath:log4j2-dev.xml
#  path: /home/binji/logs/spring-boot-demo/${env}

# mybatis映射文件
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml