server:
  servlet:
    context-path: /
  port: 8111

logging:
  config: classpath:log4j2-dev.xml
  path: /home/binji/logs/spring-boot-demo/${env}

env: dev

spring:
  # 配置缓存注解
  cache:
    type: redis
    cache-names: redisCache
  # 缓存配置

  # 数据库配置
  datasource:
    #    url: jdbc:sqlserver://121.40.131.13:1433;DatabaseName=xd20191129;
    #    username: sa
    #    password: Sa@123456
    url: jdbc:sqlserver://122.112.193.102:1433;DatabaseName=czk;
    username: sa
    password: Sa@123456
    #    url: jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=Asia/Shanghai
    #    username: root
    #    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 初始化大小，最小，最大
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery:  select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    tomcat:
      # 连接最大活跃数
      max-active: 50
      # 连接最大等待数
      max-idle: 10
      # 获取连接等待时长，单位ms
      max-wait: 10000
      # 连接池初始化连接数
      initial-size: 5




## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:Mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.jib.wwyt.model,com.jib.wwyt.mapper  # 注意：对应实体类的路径
  configuration:
    call-setters-on-nulls: true  #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏



# 设置单个文件最大内存
multipart:
  maxFileSize: 10Mb
  # 设置所有文件最大内存

  maxRequestSize: 10Mb
# 自定义文件上传路径
web:
  #  upload-path: D:/Develop/Files/Photos
  #访问PC端上传的文件
  pcurl: 172.103.20.35:8808
